### ISSUE TITLE
make: *** [build] Error 128, fatal: unable to access 'https://git.oxfordnanolabs.local/bsipos/ont-assembly-polish.git/': Could not resolve host: git.oxfordnanolabs.local

### ISSUE THREAD

**Issue by johnsolk** [nanoporetech/ont-assembly-polish#7] opened 2017-08-10 15:05 UTC
Hello!

Encountered this Error with `sudo make build` on a fresh Ubuntu 16.04 instance on [XSEDE's Jetstream VM platform](https://portal.xsede.org/jetstream). Seems unable to reach host: `git.oxfordnanolabs.local`. Any ideas what might be the cause and how I can fix?

Steps taken:

```
sudo apt-get -y update
wget -qO- https://get.docker.com/ | sudo sh
sudo usermod -aG docker ljcohen
git clone https://github.com/nanoporetech/ont-assembly-polish.git
cd ont-assembly-polish/
cd docker
sudo make build
```

Am eager to get this pipeline working for several ONT and Illumina data sets. 

Thank you!
Lisa

```
Removing intermediate container 1b13998aec28
Step 10/13 : WORKDIR /home
 ---> 8ea414c482cc
Removing intermediate container 03118deebe65
Step 11/13 : ARG CACHEBUST
 ---> Running in 477ce3a32735
 ---> 07873f98a266
Removing intermediate container 477ce3a32735
Step 12/13 : RUN DUMMY=${CACHEBUST} GIT_SSL_NO_VERIFY=wizardry git clone https://git.oxfordnanolabs.local/bsipos/ont-assembly-polish.git
 ---> Running in 9a411e98566d
Cloning into 'ont-assembly-polish'...
fatal: unable to access 'https://git.oxfordnanolabs.local/bsipos/ont-assembly-polish.git/': Could not resolve host: git.oxfordnanolabs.local
The command '/bin/sh -c DUMMY=${CACHEBUST} GIT_SSL_NO_VERIFY=wizardry git clone https://git.oxfordnanolabs.local/bsipos/ont-assembly-polish.git' returned a non-zero code: 128
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 128
```

**Comment by bsipos** [comment] 2017-08-10 15:49
Hello. This was caused by a bug in the docker file. It is fixed now, please try to build again after you pulled the latest commit.

**Closed as completed by bsipos** 2017-08-10 15:49 UTC

**Comment by johnsolk** [comment] 2017-08-11 14:45
Thank you! Seems to be working now. :)
